# Generated by Django 3.2.8 on 2021-11-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211028_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='car_condition',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='car_year',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='carrier_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='delivery_city',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='delivery_zip',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='move_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='surname',
        ),
        migrations.AddField(
            model_name='lead',
            name='dropoff_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='dropoff_state_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='dropoff_zip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='estimated_ship_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='make1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='model1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='pickup_state_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ship_via_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_runs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_type_id1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='year1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pickup_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pickup_zip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
