# Generated by Django 3.2.8 on 2021-11-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_lead_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='last_changed',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='time_created',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
