# Generated by Django 3.2.8 on 2021-11-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211102_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='priority',
        ),
    ]
