# Generated by Django 3.2.8 on 2021-11-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_lead_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_changed',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='time_created',
        ),
        migrations.AlterField(
            model_name='lead',
            name='estimated_ship_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
