# Generated by Django 3.2.8 on 2021-11-02 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_lead_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_changed',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2021, 11, 2, 13, 15, 32, 653664)),
        ),
        migrations.AddField(
            model_name='lead',
            name='time_created',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2021, 11, 2, 13, 15, 32, 653643)),
        ),
    ]
