# Generated by Django 3.2.8 on 2021-11-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211102_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='last_changed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
