# Generated by Django 3.2.8 on 2021-11-02 13:54

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211102_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=enumchoicefield.fields.EnumChoiceField(default=app.models.PRIORITY(1), enum_class=app.models.PRIORITY, max_length=11),
        ),
    ]
