# Generated by Django 3.2.8 on 2021-11-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_lead_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
