# Generated by Django 3.2.8 on 2021-11-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_note_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='sender',
            new_name='senderr',
        ),
    ]
